apiVersion: apps/v1
kind: Deployment
metadata:
  name: dco-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dco-app
  template:
    metadata:
      labels:
        app: dco-app
    spec:
      containers:
        - name: dco-app
          image: dco-devops-project-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: dco-app-service
spec:
  selector:
    app: dco-app
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30300
